Fix copy column mismatch
kuzudb/kuzu pull request #1432
Opened 2023-03-31 08:58 UTC by acquamarin

2023-03-31 18:25 UTC, andyfengHKU commented on src/storage/copier/rel_copier.cpp
> +    std::vector<common::property_id_t> propertyIdxes;
bro! why is a vector of id is named as property**Idxes** instead of property**Ids**. We need to fix this naming across this PR.

2023-03-31 18:25 UTC, andyfengHKU commented on src/storage/copier/table_copier.cpp
> +    std::sort(propertyIdxes.begin(), propertyIdxes.end());
now I'm thinking do we really need to sort?

2023-03-31 18:25 UTC, andyfengHKU commented on src/storage/copier/table_copier.cpp
> +    col_idx_t batchColumnIdx = getPropertyBatchColumnStartIdx();
Is there a difference between `Column` and `BatchColumn`? If not I would just use Column for simplicity ( or FileColumn if you wanna differentiate with the column used in storage)

2023-04-01 04:15 UTC, ray6080 requested changes
I'm actually confused on this PR, it seems you take a more complicated way to fix the issue, unless i'm missing something here. In my understanding, the clearest way is to change 
the `std::unordered_map<common::property_id_t, std::unique_ptr<NodeInMemColumn>> columns` in `NodeCopier` to `vector<std::unique_ptr<NodeInMemColumn>> columns`, in this way, each in mem column is aligned with a "column from (csv/parquet) file". You only need to figure out which property each "column from file" corresponds to, and keep the property id (if needed, but i doubt it, it seems you need the property id only for file path) inside the in mem column. When we populate columns, we just need to loop through "columns from file", and copy each of them into the corresponding in mem column, because these two kinds of columns are already aligned in their own vectors, so it's easy.

Let's discuss in person if you have any questions or problems.

2023-04-24 15:40 UTC, closed without merging