Npy copy
kuzudb/kuzu pull request #1734
Opened 2023-06-28 19:40 UTC by aziz-mu

This code doesn't work currently, no need to review

2023-07-06 20:22 UTC, aziz-mu commented
Note that there's still a bug in the PR - reading large (>2048 rows), multidimensional (e.g. column w/ type INT32[10]) .npy files causes an error. I'm currently working on fixing this, but if it's urgent to get this PR merged to integrate with storage changes for the next release, I propose removing the failing test (which I've done already), and creating an issue for it to be fixed soon. Happy to discuss this further

2023-07-07 13:06 UTC, ray6080 requested changes
There still seems to be some other bugs. I will take a look too.

2023-07-07 13:06 UTC, ray6080 commented on src/storage/copier/npy_reader.cpp
>  std::shared_ptr<arrow::RecordBatch> NpyReader::readBlock(common::block_idx_t blockIdx) const {
The returned result is incorrect for fixed-sized list. Arrow's fixed-sized list requires special construction. It should be something similar to this:
```
    auto buffer = std::make_shared<arrow::Buffer>(rowPointer, CopyConstants::NUM_ROWS_PER_BLOCK_FOR_NPY);
    int64_t length = std::min(CopyConstants::NUM_ROWS_PER_BLOCK_FOR_NPY, getNumRows() - rowNumber);
    std::shared_ptr<arrow::Field> field;
    std::shared_ptr<arrow::Array> arr;
    if (getNumDimensions() > 1) {
        auto elementField = std::make_shared<arrow::Field>(defaultFieldName, arrowType);
        auto fixedListArrowType = arrow::fixed_size_list(elementField, (int32_t)length);
        field = std::make_shared<arrow::Field>(defaultFieldName, fixedListArrowType);
        auto valuesArr = std::make_shared<arrow::PrimitiveArray>(arrowType, length * getNumElementsPerRow(), buffer);
        arr = arrow::FixedSizeListArray::FromArrays(valuesArr, (int32_t)getNumElementsPerRow()).ValueOrDie();
    } else {
        field = std::make_shared<arrow::Field>(defaultFieldName, arrowType);
        arr = std::make_shared<arrow::PrimitiveArray>(arrowType, length, buffer);
    }
```

2023-07-07 13:06 UTC, ray6080 commented on src/processor/operator/copy/read_npy.cpp
> +        std::vector<uint64_t> numRowsPerBlock(numRows,
This line should be incorrect.
It should be `std::vector<uint64_t> numRowsPerBlock(numBlocks, common::CopyConstants::NUM_ROWS_PER_BLOCK_FOR_NPY)`. Or 
```
        auto blockIdx = 0;
        std::vector<uint64_t> numRowsPerBlock(numBlocks);
        while (blockIdx < numBlocks) {
            numRowsPerBlock[blockIdx] = std::min(CopyConstants::NUM_ROWS_PER_BLOCK_FOR_NPY,
                numRows - (blockIdx * CopyConstants::NUM_ROWS_PER_BLOCK_FOR_NPY));
            blockIdx++;
        }
```

2023-07-08 12:35 UTC, ray6080 approved these changes

2023-07-08 12:37 UTC, merged