Acces mode (first version)
kuzudb/kuzu pull request #2089
Opened 2023-09-26 15:14 UTC by hououou

This PR is aimed at solving [issue #921](https://github.com/kuzudb/kuzu/issues/921).

Steps:
- Add a file `.lock` in each database directory.  Use this file to check the status of the database.
- When a database is started with an access mode referring to as` READ_ONLY` or `READ_WRITE` (note I use `READ_WRITE`  when the access mode is not specified), lock the `.lock` using the function` fcntl`.

Limitation
- ` fcntl` can only solve the read-write lock during different processes.  So we cannot solve the read-write lock in the same process.

2023-09-26 16:22 UTC, ray6080 reviewed
Did a pre-review while this is still a draft. please check my comments.
There are still some code not cleaned up. Let me know when it is ready for another review.

2023-09-26 16:22 UTC, ray6080 commented on examples/cpp/CMakeLists.txt
> +link_directories(../../build/debug/src)
Revert this after you're done with debugging.

2023-09-26 16:22 UTC, ray6080 commented on examples/cpp/main.cpp
Ditto. Revert changes in this file after debugging.

2023-09-26 16:22 UTC, ray6080 commented on src/common/file_utils.cpp
> +    if (lock_type != FileLockType::NO_LOCK) {
Let's not add a new `openFile` function to `FileUtils`. I believe we can merge the lock logic into existing `openFile` function. By default, `openFile` will opens a file in `NO_LOCK` mode.

Also, remember we should handle windows too (if it is doable).

2023-09-26 16:22 UTC, ray6080 commented on src/include/common/file_utils.h
> +class FileFlags {
This class should be cleaned after you merge locking logic into existing `openFile` function.

2023-09-26 16:22 UTC, ray6080 commented on src/main/database.cpp
> +void Database::CheckAccessMode() const {
CheckAccessMode -> checkAccessMode

2023-09-26 16:22 UTC, ray6080 commented on src/include/main/database.h
> +enum class AccessMode : uint8_t { UNDEFINED = 0, AUTOMATIC = 1, READ_ONLY = 2, READ_WRITE = 3};
What is `AUTOMATIC` mode? It doesn't seem to be handled. Can we get rid of it for now?

2023-09-26 16:22 UTC, ray6080 commented on test/runner/test_locking.cpp
Clean up couts.

2023-09-28 06:42 UTC, hououou commented on src/include/main/database.h
> +    std::unique_ptr<common::FileInfo> lockStatus;
is it ok? I need to hold the `.lock` file information after I open it. otherwise the lock will lose its efficacy

2023-09-28 16:47 UTC, ray6080 requested changes
Didn't look into tests yet. Will continue later.

2023-09-28 16:47 UTC, ray6080 commented on src/main/connection.cpp
> +    bool accessMode = this->database->systemConfig.access_mode == AccessMode::READ_ONLY;
accessMode -> isReadOnlyMode.

2023-09-28 16:47 UTC, ray6080 commented on src/main/connection.cpp
> +    if (accessMode && !statementReadOnly) {
L83 - L85:
```cpp
    bool isReadOnlyMode = this->database->systemConfig.access_mode == AccessMode::READ_ONLY;
    if (isReadOnlyMode && !preparedStatement->isReadOnly()) {
```

2023-09-28 16:47 UTC, ray6080 commented on src/main/database.cpp
> +    checkAccessMode();
Can we move this function inside `initDBDirAndCoreFilesIfNecessary`? You can check access mode after 
```cpp
    if (!FileUtils::fileOrPathExists(databasePath)) {
        FileUtils::createDir(databasePath);
    }
```

2023-09-28 16:47 UTC, ray6080 commented on src/main/database.cpp
> +    checkAccessMode();
Can we move this function inside `initDBDirAndCoreFilesIfNecessary`? You can check access mode after 
```cpp
    if (!FileUtils::fileOrPathExists(databasePath)) {
        FileUtils::createDir(databasePath);
    }
```

2023-09-28 16:47 UTC, ray6080 commented on src/main/database.cpp
> +        getFileFlags(systemConfig, flags, lock, true);
1. You're setting both `flags` and `lock`, why name this function as `getFileFlags`?

2023-09-28 16:47 UTC, ray6080 commented on src/main/database.cpp
> +    }
Remove L88 to L90 after you move this function into `initDBDirAndCoreFilesIfNecessary`.

2023-09-28 16:47 UTC, ray6080 commented on src/main/database.cpp
> +    if (!FileUtils::fileOrPathExists(databasePath)) {
I think we should check if the access mode is set to READ_ONLY, if so, we should throw an exception "Cannot create an empty database under READ ONLY mode."

2023-09-28 16:47 UTC, ray6080 commented on src/main/database.cpp
> +void getFileFlags(SystemConfig systemConfig, int& flags, FileLockType& lock, bool create_new) {
1. Simply pass in `accessMode` is enough, no need to pass in the whole SystemConfig.
2. Make this function static.
3. Rename to `getLockFileFlagsAndType`.
4. Reorder your params, so your input and output are separate and together. better for reading. for example `getFileFlags(SystemConfig systemConfig, bool create_new, int& flags, FileLockType& lock)`

2023-09-28 16:47 UTC, ray6080 commented on src/main/database.cpp
> +void getFileFlags(SystemConfig systemConfig, int& flags, FileLockType& lock, bool create_new) {
`create_new` -> `createNew`. Be careful with your code style. We follow camelCase, and functions start with lower case char.

2023-09-28 16:47 UTC, ray6080 commented on src/main/database.cpp
> +    }
If it's createNew, do we need to set flags to `O_WRONLY`?, will `O_RDWR` be fine?
If so, I think this piece of code can be re-organized as following:
```cpp
    flags = systemConfig.access_mode == AccessMode::READ_ONLY ? O_RDONLY : O_RDWR;
    if (create_new) {
        assert(flags == O_RDWR);
        flags |= O_CREAT;
    }
    lock = systemConfig.access_mode == AccessMode::READ_ONLY ? FileLockType::READ_LOCK : FileLockType::WRITE_LOCK;
```

2023-09-28 16:47 UTC, ray6080 commented on src/include/main/database.h
> +#include "common/file_utils.h"
I don't think you need to include `file_utils.h` in header file. Be careful when adding includes to header files, especially under `common` and `main`, the former one is included in lots of places, and the latter one exposed to clients.
Can you double check if you can remove the include? instead, add forward declaration here https://github.com/kuzudb/kuzu/blob/f05d34893d54b4d75708087a844e6c356907ac84/src/include/main/kuzu_fwd.h#L32

2023-09-28 16:47 UTC, ray6080 requested changes
Didn't look into tests yet. Will continue later when you finalize changes to tests.

2023-10-17 03:14 UTC, ray6080 approved these changes

2023-10-17 12:32 UTC, merged