Ninja ci
kuzudb/kuzu pull request #2264
Opened 2023-10-25 11:48 UTC by mewim

2023-10-25 13:35 UTC, Riolku commented
We should probably use gmake in at least one of the jobs. I don't think it particularly matters which, but we should test that gmake still works.

2023-10-25 13:43 UTC, Riolku commented
Benefit of doing it in GCC is build with ASAN and benchmark runs sooner. Benefit of doing it in clang means any clang tidy errors are shown earlier.

2023-10-25 14:50 UTC, mewim commented
I did not switch the benchmark to use ninja so gmake is being tested in benchmark. Is it sufficient or do you prefer to use gmake in a test?

2023-10-25 14:54 UTC, Riolku commented
I think I'd rather have the benchmark use ninja and clang use gmake, because that should give us the fastest overall CI speeds.

2023-10-25 15:10 UTC, mewim commented
OK I will redeploy the benchmark runners some time and update this...

2023-10-26 05:55 UTC, andyfengHKU approved these changes

2023-10-26 09:51 UTC, mewim commented
@Riolku I have updated and redeployed the benchmark runners to use Ninja build and switched clang build job back to using gmake. I also removed several unneeded dependencies from the benchmark runner.

2023-10-26 13:41 UTC, Riolku approved these changes

2023-10-26 13:41 UTC, Riolku commented on .github/workflows/ci-workflow.yml
> +      NUM_THREADS: 30
If you use an env var, remove the parameter to make on the later line.

2023-10-26 15:00 UTC, Riolku requested changes

2023-10-26 15:00 UTC, Riolku commented on benchmark/Dockerfile
> +
It sort of looks like we forgot to install npm... https://github.com/kuzudb/kuzu/actions/runs/6655831578/job/18087424945?pr=2273 I have a failure here.

2023-10-26 15:02 UTC, Riolku commented on benchmark/Dockerfile
> +
Nevermind, that's because benchmark no longer needs npm. We should merge this soon then so CI isn't broken for too long.

2023-10-26 15:02 UTC, Riolku approved these changes

2023-10-26 15:08 UTC, merged