Allow explicit cast between varlist CAST(var, varlist type)
kuzudb/kuzu pull request #2386
Opened 2023-11-10 20:49 UTC by AEsir777

2023-11-10 22:44 UTC, acquamarin requested changes

2023-11-10 22:44 UTC, acquamarin commented on src/function/vector_cast_functions.cpp
> +        throw ConversionException{stringFormat("Unsupported casting function from {} to {}.",
Use //lcov_excl_start

2023-11-10 22:44 UTC, acquamarin commented on src/include/function/unary_function_executor.h
> +        auto inputChildVector = (common::ListVector::getDataVector(&operand));
remove the redundant '()'

2023-11-10 22:44 UTC, acquamarin commented on src/include/function/unary_function_executor.h
> +        KU_ASSERT(operand.dataType.getLogicalTypeID() == common::LogicalTypeID::VAR_LIST &&
This executor looks incorrect to me:
1. The executor doesn't handle nulls correctly. We should loop through each value in the operand and set null in the result accordingly.
2. If the operand state is selected, we should skip casting unselected elements.

2023-11-10 22:44 UTC, acquamarin commented on src/function/vector_cast_functions.cpp
> +static void varListCastExecFunction(
As we discussed, we don't need to template this function

2023-11-13 21:34 UTC, AEsir777 commented on src/include/function/unary_function_executor.h
> +                OP_WRAPPER::template operation<OPERAND_TYPE, RESULT_TYPE, FUNC>(
This is covered

2023-11-14 16:08 UTC, acquamarin approved these changes

2023-11-14 16:16 UTC, AEsir777 commented on src/function/vector_cast_functions.cpp
> +    resultVector->setNullFromBits(inputVector->getNullMaskData(), 0, 0, listEntrySize);
This is a private function for NullMask. `setNullFromBits` is only public method, which calls `setNullFromBits`.

2023-11-14 17:42 UTC, merged