fix IMPORT_DATABASE path
kuzudb/kuzu pull request #3063
Opened 2024-03-15 00:48 UTC by hououou

2024-03-15 14:17 UTC, andyfengHKU requested changes
I'm assuming this PR is to fix a bug. But I don't see a test reproducing that bug.

2024-03-15 14:17 UTC, andyfengHKU commented on src/include/common/file_system/file_system.h
> +    std::string pathSeparator();
make static and move to cpp.

2024-03-15 14:17 UTC, andyfengHKU commented on src/include/common/file_system/file_system.h
> +    std::string convertSeparators(const std::string& path);
ditto

2024-03-15 14:17 UTC, andyfengHKU commented on src/include/common/file_system/file_system.h
> +    std::string extractName(const std::string& path);
comment what this function is doing. Extract name for a given path is ambiguous.

2024-03-15 14:17 UTC, andyfengHKU commented on src/binder/bind/bind_import_database.cpp
> +    for (auto& parsedStatement : parsedStatements) {
Add comment about what modification we are doing for each COPY FROM statement.

2024-03-16 03:00 UTC, acquamarin commented on src/include/common/file_system/file_system.h
> +    std::string pathSeparator();
I would suggest not adding more functions to the FileSystem class since any changes to the fileSystem class may require re-compilation of extensions.

2024-03-16 03:00 UTC, acquamarin commented on src/include/common/file_system/file_system.h
> +    std::string pathSeparator();
getPathSeparator()

2024-03-21 22:38 UTC, acquamarin approved these changes
As we discussed, we should parse the csvOptions when exporting. If the csvOptions have special characters, we should escape/quote

2024-03-21 22:38 UTC, acquamarin commented on src/binder/bind/bind_import_database.cpp
> +std::string getQueryFromFile(
make it static

2024-03-21 22:38 UTC, acquamarin commented on src/binder/bind/bind_import_database.cpp
> +        finalQueryStatements += csvQuery;
I think you can refactor line 48 to 61 to a function called getCopyStatement?

2024-03-21 22:38 UTC, acquamarin commented on src/processor/operator/persistent/export_db.cpp
> +    ss << tableName << " FROM \"" << tableName;
I would suggset using stringFormat for better readability : ss << common::stringFormat("copy from {} {}", tableName, fileTypeStr, csvConfig);

2024-03-22 20:59 UTC, andyfengHKU approved these changes

2024-03-22 21:22 UTC, merged