Updated progress bar for asynchronous queries
kuzudb/kuzu pull request #3665
Opened 2024-06-18 17:49 UTC by MSebanc

# Description

Improved progress bar handling of asynchronous query calls

# Contributor agreement

- [x] I have read and agree to the [Contributor Agreement](https://github.com/kuzudb/kuzu/blob/master/CLA.md).

2024-06-18 20:47 UTC, andyfengHKU requested changes
Overall LGTM but I need to take another look for system level query id.

Also @mewim should take a look on the js part.

2024-06-18 20:47 UTC, andyfengHKU commented on src/main/connection.cpp
> +std::unique_ptr<QueryResult> Connection::executeWithParamsWithId(
Do we need this? I'm pretty sure if we prepare, we cannot support multiple statements. You can add a test case on this.

2024-06-18 20:47 UTC, andyfengHKU commented on src/include/common/task_system/progress_bar.h
> +    void finishPipeline(std::string id);
better to rename to queryID and comment when this is needed.

2024-06-18 20:47 UTC, andyfengHKU commented on src/include/main/connection.h
> +    std::unique_ptr<QueryResult> executeWithParamsWithId(PreparedStatement* preparedStatement,
I would remove this.

2024-06-18 20:47 UTC, andyfengHKU commented on src/include/processor/execution_context.h
> +        : profiler{profiler}, clientContext{clientContext} {
I think @ray6080 will need a system level query id soon. So let's make this id generated from database which you will need a counter and a lock. Then ExecutionContext should always be created with an id and does not need to generate one in the constructor.


Also I would suggest using a integer based id.

2024-06-18 20:47 UTC, andyfengHKU commented on src/main/client_context.cpp
> +    auto executionContext = std::make_unique<ExecutionContext>(profiler.get(), this, id);
So here try to get a system level id from database.

2024-06-18 20:47 UTC, andyfengHKU commented on src/main/client_context.cpp
> +        progressBar->endProgress(executionContext->queryId);
We prefer ID over Id as a convention I think.

2024-06-18 20:47 UTC, andyfengHKU commented on tools/nodejs_api/src_cpp/include/node_connection.h
> +        std::string id = common::UUID::toString(
ditto here try to get a system level id from database.

2024-06-18 20:47 UTC, andyfengHKU commented on src/include/main/client_context.h
> +        std::unordered_map<std::string, std::unique_ptr<common::Value>> inputParams,
ditto I would not change this API given we don't have multi query in a prepared statement.

2024-06-19 18:27 UTC, mewim commented
I do not think we should print anything from the Node.js API side. If it is for debug only, you should delete the printing.

2024-06-19 18:30 UTC, andyfengHKU approved these changes

2024-06-19 18:30 UTC, andyfengHKU commented on src/include/common/task_system/progress_bar_display.h
> +    // identify the query
Say queryID is needed when we track progress of multiple queries asynchronously.

2024-06-19 18:30 UTC, andyfengHKU commented on src/include/processor/execution_context.h
> +#include "common/types/uuid.h"
this should be no longer needed.

2024-06-19 18:30 UTC, andyfengHKU commented on src/include/main/database.h
> +    uint64_t queryID;
Let's wrap this into a struct called QueryIDGenerator

2024-06-19 18:30 UTC, andyfengHKU commented on src/include/main/database.h
> +    uint64_t getNextQueryID();
ditto move to QueryIDGenerator.

2024-06-19 18:30 UTC, andyfengHKU commented on tools/nodejs_api/src_cpp/include/node_progress_bar_display.h
> +#include "common/task_system/terminal_progress_bar_display.h"
include terminal_progress_bar does not sound correct to me.

2024-06-19 18:30 UTC, andyfengHKU commented on tools/nodejs_api/src_cpp/node_connection.cpp
> +        std::make_shared<NodeProgressBarDisplay>());
not related to this PR. But I think you might be able to use unique_ptr for display in ProgressBar class.

2024-06-20 18:28 UTC, andyfengHKU commented on tools/nodejs_api/src_cpp/include/node_connection.h
> +#include "common/types/uuid.h"
remove this

2024-06-20 20:49 UTC, merged