Allow CALL functions without RETURN clause
kuzudb/kuzu pull request #4315
Opened 2024-09-27 19:39 UTC by royi-luo

# Description

We have some "void" CALL functions such as `clear_warnings()`, this removes the need for these functions to return any values.

To do this, we modify the grammar to break `oC_ReadingClause` into `oC_MandatoryReturnReadingClause` (for clauses like `MATCH` and `LOAD_FROM`) and `oC_OptionalReturnReadingClause` (for CALL clauses). For optional return reading clauses, the check for `RETURN` is moved to the binding phase and only throws if the `CALL` clause returns non-empty output.

Fixes https://github.com/kuzudb/kuzu/issues/4250

# Contributor agreement

- [ ] I have read and agree to the [Contributor Agreement](https://github.com/kuzudb/kuzu/blob/master/CLA.md).

2024-09-28 00:03 UTC, royi-luo commented on scripts/antlr4/Cypher.g4
>      : ( kU_ProjectGraph SP? )? CALL SP oC_FunctionInvocation (SP? oC_Where)? ;
Is `CALL COUNT(*)` or `CALL CAST` a thing or can I remove `kU_InQueryBuiltInCall` altogether?

2024-09-30 08:39 UTC, andyfengHKU requested changes
hmmmm, this is wrong way to handle `CALL clear_warning()`.

Don't compile it as a `SingleQuery` or `TableFunction`.

Compile it as as a `StandaloneCall`

2024-09-30 14:04 UTC, royi-luo commented
> hmmmm, this is wrong way to handle `CALL clear_warning()`.
> 
> Don't compile it as a `SingleQuery` or `TableFunction`.
> 
> Compile it as a `StandaloneCall`.
> 
> I suggest let @acquamarin take over or mentor.

I see, will update and let @acquamarin know when I'm done

2024-09-30 14:07 UTC, andyfengHKU commented
> > hmmmm, this is wrong way to handle `CALL clear_warning()`.
> > Don't compile it as a `SingleQuery` or `TableFunction`.
> > Compile it as a `StandaloneCall`.
> > I suggest let @acquamarin take over or mentor.
> 
> I see, will update and let @acquamarin know when I'm done

Talk to @acquamarin before u start. I don't know if he plans to take over or not.

2024-09-30 17:28 UTC, royi-luo commented
Closing as @acquamarin is taking this over.

2024-09-30 17:28 UTC, closed without merging