Prototype of vector index
kuzudb/kuzu pull request #4578
Opened 2024-12-02 04:56 UTC by ray6080

# Description

2024-12-19 04:25 UTC, semihsalihoglu-uw requested changes
I have several comments throughout but most are small or medium-level. My broader comments are these. To organize my thoughts, let me first list several problems in the current implementation, which I will list first. Then I will propose some changes that I think address them.

Problem 1: HNSWGraph class design: There are several problems here. 
Problem 1.1: Some of the functions in HNSWGraph are not used in OnDiskHNSWGraph, which only support searching. So any insertion-related functions are marked as UNREACHABLE but still inherited by OnDiskHNSWGraph, e.g., createDirectedEdge, finalize, shrink etc. You have a similar problem in the HNSWIndex class hiearchy.
Problem 1.2: I am not convinced you need OnDiskHNSWGraph at all. We have an OnDiskGraph implementation that seems to support all of the functionality that you need, which is getting the neighbors of nodes from a rel table. OnDiskGraph is able to do this already and provides an iterator interface.


Problem 2: HNSWIndex design: You seem to have a similar (but opposite) problem as Problem 1.1. How it looks like HNSWIndex contains search-related functions, such as searchUpperLayer and searchLowerLayer, that are not needed by InMemHNSWIndex. In some sense, InMemHNSWIndex also needs search functions for upper and lower layer to do insertions but for  InMemHNSWIndex these can be the same function (see my comment in Problem 3 below).

Problem 3: HNSWIndex insert functions: Your InMemHNSWIndex::insertToUpperLayer and InMemHNSWIndex::insertToLowerLayer functions deviate from the design doc. These can actually be the same function that takes in an entry point (the first node).

Problem 3 is a separate problem. It's more like a bug, and not a design decision. For the Problem 1 and 2, I think we can move to the following design:
- Remove HNSWGraph class hierarchy and only have an InMemHNSWGraph class: If you can re-use OnDiskGraph as is, we don't need to form a class hierarchy here and can only have an InMemHNSWGraph class. You could consider renaming this to HNSWGraphBuilder because the main functionality of this class is not that it's an in-memory implementation but that it's used for building the HNSWGraph. In general, I find it better to give class and field names based on functionality.
- HNSWIndex class hierarchy: Here we could still have the same class hierarchy of HNSWIndex (or BaseHNSWIndex), InMemHNSWIndex (or HNSWIndexBuilder), and OnDiskHNSWIndex. HNSWIndex (or BaseHNSWIndex) would contain common fields such as config Embedding* field. InMemHNSWIndex would have two InMemHNSWGraph fields and coordinate inserting into both lower and upper InMemHNSWGraph (though with a single common search function and correct upper layer insertion algorithm). Finally, OnDiskHNSWIndex would contain two OnDiskGraphs for upper and lower layers and implement the search functionality.


Other than that, I have several concerns about sitting down and designing with Ziyi a long term solution to our binding, planning, and mapping phases of table functions. I'm not clear about the clear roadmap to how we build additional indices in the system as extensions and what interfaces the extension builder implements. I see some rewriting into CREATE REL TABLE statements but then because of how we create rel tables, there is some custom logic that gets deep into the map_copy_rel. That does not seem like how we can create an extension framework. We need to think about clear interfaces and contracts between the core system and extensions that will build indices. I think we can sacrifice some efficiency here if we have to.

2025-01-07 03:16 UTC, ray6080 commented on src/include/function/table/hnsw/hnsw_index_functions.h
> +    QueryHNSWIndexBindData(binder::expression_vector columns, common::table_id_t indexTableID,
Done.

2025-01-07 03:18 UTC, ray6080 commented on src/catalog/catalog_entry/catalog_entry.cpp
> +        // TODO(Ziyi/Guodong): This should be reworked. Hack for now for HNSW only.
It's part of the TODO item "Serialize/deSerialize index entry." in the todo list. You can check it here https://github.com/kuzudb/internal/issues/6#issuecomment-2497024545.

2025-01-07 03:21 UTC, ray6080 commented on src/include/function/table/hnsw/hnsw_index_functions.h
> +struct QueryHNSWIndexBindData final : SimpleTableFuncBindData {
I temporarily moved storage level fields into the shared state, which is a fine solution, before I can start to refactor the mapping of table functions. Put a todo item under "refactoring" category for now.

2025-01-07 03:21 UTC, ray6080 commented on src/function/table/call/hnsw/create_hnsw_index.cpp
> +// TODO(Guodong): Should abstract this common logic with fts into index entry binding.
Done.

2025-01-07 03:21 UTC, ray6080 commented on src/function/table/call/hnsw/drop_hnsw_index.cpp
> +static void validateTableAndIndexExists(const main::ClientContext& context,
Done.

2025-01-07 03:22 UTC, ray6080 commented on src/catalog/catalog_entry/hnsw_index_catalog_entry.cpp
> +    // TODO(Ziyi): tableID and indexName should be serialized inside IndexCatalogEntry.
Ditto https://github.com/kuzudb/kuzu/pull/4578#discussion_r1904855694

2025-01-07 03:23 UTC, ray6080 commented on src/function/table/call/hnsw/create_hnsw_index.cpp
> +// TODO(Guodong/Ziyi): Change bindFunc input to const *.
Done.

2025-01-07 03:23 UTC, ray6080 commented on src/function/table/call/hnsw/create_hnsw_index.cpp
> +// TODO(Guodong/Ziyi): Change initSharedState input to const &.
Done.

2025-01-07 03:23 UTC, ray6080 commented on src/function/table/call/hnsw/create_hnsw_index.cpp
> +    // TODO(Guodong): Find a way to parallel the scan of the initial caching.
Put as an todo item under "Optimizations".

2025-01-07 03:24 UTC, ray6080 commented on src/function/table/call/hnsw/create_hnsw_index.cpp
> +// TODO(Guodong/Ziyi): Change tableFunc input to const &.
Done.

2025-01-07 03:27 UTC, ray6080 commented on src/function/table/call/hnsw/create_hnsw_index.cpp
> +static offset_t tableFunc(TableFuncInput& input, TableFuncOutput&) {
I doubt renaming is a good idea in this case. The `tableFunc` interface serves the same purpose as `getNextTuplesInternal` in a physical operator, which is a common interface across all physical operators. In my view, keeping it as is makes it clearer that this as the main entry point of function execution.

2025-01-07 03:28 UTC, ray6080 commented on src/function/table/call/hnsw/create_hnsw_index.cpp
> +    auto upperRelTableID = catalog->getTableID(context->clientContext->getTx(),
We have an todo item on virtual tables in both my and @acquamarin 's todo list.

2025-01-07 03:28 UTC, ray6080 commented on src/function/table/call/hnsw/create_hnsw_index.cpp
> +static std::string createHNSWIndexTables(main::ClientContext&, const TableFuncBindData& bindData) {
Updated the PR description for this.

2025-01-07 03:29 UTC, ray6080 commented on src/function/table/call/hnsw/create_hnsw_index.cpp
> +    // TODO(Guodong): Should handle the case a node is deleted or its vector is null.
Moved to the todo list under "Usability".

2025-01-07 03:29 UTC, ray6080 commented on src/function/table/call/hnsw/create_hnsw_index.cpp
> +// TODO(Guodong): Should abstract this common logic with fts into index entry binding.
Done.

2025-01-07 03:29 UTC, ray6080 commented on src/function/table/call/hnsw/query_hnsw_index.cpp
> +    return std::make_unique<QueryHNSWIndexBindData>(std::move(columns),
Done.

2025-01-07 03:29 UTC, ray6080 commented on src/function/table/call/hnsw/query_hnsw_index.cpp
> +    return std::make_unique<QueryHNSWIndexBindData>(std::move(columns),
Done.

2025-01-07 03:30 UTC, ray6080 commented on src/function/table/call/hnsw/query_hnsw_index.cpp
> +static common::offset_t tableFunc(TableFuncInput& input, TableFuncOutput& output) {
See here https://github.com/kuzudb/kuzu/pull/4578#discussion_r1904864046.

2025-01-07 03:33 UTC, ray6080 commented on src/function/table/call/hnsw/query_hnsw_index.cpp
> +    if (localState->numRowsOutput >= localState->result->size()) {
This is to handle the case when the search output is larger than 2048, so `tableFunc` should copy the result from `localState->result` to `output.dataChunk`.

2025-01-07 03:39 UTC, ray6080 commented on src/include/catalog/catalog_entry/hnsw_index_catalog_entry.h
> +        common::offset_t upperEntryPoint, common::offset_t lowerEntryPoint,
Put this as an todo under "Refactoring". I'm leaving this as TODO as I want to do this after we move the index to extensions.

```
Move index storage level information (lower/upper entry point) out of HNSWIndexCatalogEntry. Should keep an HNSWIndex in StorageManager and the index will be serialized in metatada.kz.
```

2025-01-07 03:41 UTC, ray6080 commented on src/main/client_context.cpp
> +            continue;
See #4633.

2025-01-07 03:42 UTC, ray6080 commented on src/include/storage/index/hnsw_graph.h
> +    virtual float* getEmebdding(common::offset_t offset,
Done.

2025-01-07 03:43 UTC, ray6080 commented on src/include/storage/index/hnsw_index.h
> +    // Return the entry point of the lower layer graph that is searched from the upper layer graph.
Outdated now.

2025-01-07 03:44 UTC, ray6080 commented on src/include/storage/index/hnsw_index.h
> +    static constexpr int64_t INSERT_TO_UPPER_LAYER_PROB_THRESHOLD = 95;
Removed this. I forgot to clean this up after added the `HNSWIndexConfig`.

2025-01-07 03:45 UTC, ray6080 commented on src/include/storage/index/hnsw_graph.h
> +    // TODO(Guodong): Should move these to local state.
Done.

2025-01-07 03:52 UTC, ray6080 commented on src/include/storage/index/hnsw_graph.h
> +    common::length_t maxDegree;
I think I still prefer `maxConnectivity` over `m`, as it can cover both `m` and `m0` for both lower and upper layers.

2025-01-07 03:53 UTC, ray6080 commented on src/include/storage/index/hnsw_graph.h
> +    // Cacheed data structures used to read from table.
Removed.

2025-01-07 03:53 UTC, ray6080 commented on src/include/storage/index/hnsw_graph.h
> +    // TODO(Guodong): Should move these to local state.
Done

2025-01-07 03:55 UTC, ray6080 commented on src/include/storage/index/hnsw_graph.h
> +// of the index, but improves the performance by avoiding random reads from disk. Though we need
Removed from the code. It is moved into the PR description.

2025-01-07 03:55 UTC, ray6080 commented on src/include/storage/index/hnsw_graph.h
> +// TODO: There should be a derived SparseInMemHNSWGraph, which is optimized for the upper graph of
It is in the todo list under "Optimizations".

2025-01-07 03:57 UTC, ray6080 commented on src/storage/index/hnsw_graph.cpp
> +    // Note that we omit transaction local data here.
We don't allow creating an index in a manual transaction for now. So there should be no transaction local data to be handled. I removed the comment.

2025-01-07 03:59 UTC, ray6080 commented on src/storage/index/hnsw_graph.cpp
> +    // TODO: Refactor how we init scanState object.
Moved to an todo item under "Refactoring". This should touch code outside the scope of vector index, which I think better to do in a separate PR.

2025-01-07 05:15 UTC, ray6080 commented on src/processor/operator/partitioner.cpp
> +// TODO(Guodong): Enable partitioning for one direction only.
Removed. This will not be handled in this PR, but separately as we address #4320

2025-01-07 05:16 UTC, ray6080 commented on src/planner/plan/append_simple.cpp
> +        // TODO(Xiyang): Is the following line necessary?
Done.

2025-01-07 05:16 UTC, ray6080 commented on test/test_files/function/hnsw/hnsw_small.test
> +-CASE DropNonExistHNSWIndex
Done.

2025-01-07 05:25 UTC, ray6080 commented on test/test_files/function/hnsw/hnsw_small.test
> +-CASE CreateHNSWError
Renamed to `InvalidHNSWIndexColumnType`.

2025-01-07 05:26 UTC, ray6080 commented on test/test_files/function/hnsw/hnsw_small.test
> +-CASE QueryHNSWError
Renamed to `MismatchedQueryVectorDimension`.

2025-01-07 05:26 UTC, ray6080 commented on test/test_files/function/hnsw/hnsw_small.test
> +1|_e_hnsw_index_UPPER|REL|local(kuzu)|
Yep

2025-01-07 05:29 UTC, ray6080 commented on src/storage/index/hnsw_config.cpp
> +            throw common::BinderException{"Unrecognized optional parameter: " + name};
That sounds good. Added function name.

2025-01-07 05:40 UTC, ray6080 commented on src/processor/map/map_copy_from.cpp
> +        case BoundCopyFromInfo::CopyFromType::HNSW_INDEX: {
Reworked the logic here to make it more clear. Now we first switch on if the copy from type is a table or a HNSW index, then if it's table, we switch on table type (node or rel).

For longer term, I think we should resolve this with a customized map_func implementation in table function calls. I can start working on this once we start to move the index to extensions.

2025-01-07 05:52 UTC, ray6080 commented on src/optimizer/acc_hash_join_optimizer.cpp
> +    if (hashJoin.getSIPInfo().direction != SIPDirection::FORCE_BUILD_TO_PROBE &&
Right now, we always require there is a filter on the build side to trigger the sip passing on master. The `FORCE_BUILD_TO_PROBE` flag is to force sip passing from the build side to probe side when we're joining index search result (on the build side. we assume index search result to be small, i.e. k is usually small) with the base node table (on the probe side).

An example is as follows:
```
CALL QUERY_HNSW_INDEX('person', 'person_vector_index', [0.1, 0.2, ...], 100) 
RETURN nn.name, _distance;
```
The probe side is `SCAN('person')`, and the build side is `QUERY_HNSW_INDEX`.

2025-01-07 05:56 UTC, ray6080 commented on src/processor/map/map_ddl.cpp
> +#include "processor/expression_mapper.h"
Yes. This is due to that I removed `#include "expression_mapper.h"` from `plan_mapper.h`.

2025-01-07 06:09 UTC, ray6080 commented on src/storage/index/hnsw_graph.cpp
> +        if (nbr == common::INVALID_OFFSET) {
Done.

2025-01-07 06:14 UTC, ray6080 commented on src/storage/store/csr_chunked_node_group.cpp
> +    if (randomLookup) {
This is an performance optimization to avoid caching CSR header during the scan of rels, as during index search, the read is more random and usually in a small size, so the cache of whole CSR header for a node group doesn't help but imposes overheads.

Maybe I should separate this optimization into a follow-up PR to make it more clear.

2025-01-07 06:14 UTC, ray6080 commented on src/storage/store/csr_chunked_node_group.cpp
> +    if (randomLookup) {
https://github.com/kuzudb/kuzu/pull/4578#discussion_r1904953002

2025-01-07 06:14 UTC, ray6080 commented on src/storage/store/csr_chunked_node_group.cpp
> +    if (randomLookup) {
https://github.com/kuzudb/kuzu/pull/4578#discussion_r1904953002

2025-01-07 06:15 UTC, ray6080 commented on src/storage/store/csr_node_group.cpp
> +    if (relScanState.randomLookup) {
https://github.com/kuzudb/kuzu/pull/4578#discussion_r1904953002

2025-01-07 09:57 UTC, ray6080 commented on test/test_files/function/hnsw/hnsw_small.test
> +-CASE CreateSmallHNSW8DimEfc
The test is reworked as `CreateHNSWIndexWithInvalidOptions`.
I realize it makes more sense to test invalid options rather than valid ones. As changes on options should only be testable if we check the recall.

2025-01-07 09:58 UTC, ray6080 commented on test/test_files/function/hnsw/hnsw_small.test
> +-CASE CreateSmallHNSW8DimM
https://github.com/kuzudb/kuzu/pull/4578#discussion_r1905197933

2025-01-07 09:58 UTC, ray6080 commented on test/test_files/function/hnsw/hnsw_small.test
> +-CASE CreateSmallHNSW8DimPlAlpha
https://github.com/kuzudb/kuzu/pull/4578#discussion_r1905197933

2025-01-07 09:58 UTC, ray6080 commented on test/test_files/function/hnsw/hnsw_small.test
> +-CASE CreateSmallHNSW8DimEfs
https://github.com/kuzudb/kuzu/pull/4578#discussion_r1905197933

2025-01-12 04:54 UTC, semihsalihoglu-uw approved these changes
Very clean PR. I'm especially happy to see the use of OnDiskGraph. 

I have a few minor comments and request to add a few more tests for edge cases.

2025-01-12 04:54 UTC, semihsalihoglu-uw commented on src/storage/index/hnsw_graph.cpp
> +    std::vector<common::column_id_t> columnIDs;
I hope one day we can hide all these scan-related code behind iterator interfaces so all of these lower-level scan related code can be hidden from the indices, similar to how on-disk graph edge scanners hide the scan logic from GDS algorithms. Many other features we develope will need to scan raw tuples and it looks like we are repeating the code of how to scan data. Ideally, we should just do the following:
```
itr = NodeTable.getColumnScanIterator<int64>(columnID)
while (itr.hasNext()) {
   data->append(itr.getNext());
}
```
And the scanIterator does all the optimizations and boilerplate code that needs to be done. The person developing the Index doesn't need to know how that was done.

2025-01-12 04:54 UTC, semihsalihoglu-uw commented on src/storage/index/hnsw_index.cpp
> +    if (currentLen >= info.maxDegree) {
This maxDegree is degreeThresholdToShrink, right?

2025-01-12 04:54 UTC, semihsalihoglu-uw commented on src/function/table/call/hnsw/query_hnsw_index.cpp
> +        index->setLowerEntryPoint(bindData->boundInput.indexEntry->getLowerEntryPoint());
I'm confused about this. Why are you setting the lowerEntryPoint to something here? The idea is that the lower entry point is found by a search in the upper layer. I was expecting this to be set somewhere inside the index->search(...) function below.

2025-01-12 04:54 UTC, semihsalihoglu-uw commented on src/function/table/call/hnsw/query_hnsw_index.cpp
> +    if (localState->numRowsOutput >= localState->result->size()) {
A separate question that this if condition made me think: Do you handle edge cases when there is 0 or 1 vectors in the table and someone tries to create an index? Technically, in either case, we should not error but if it easier, we can error for 0 for now (since there is nothing to index). But if there is only 1 or 2 etc vertices, we should certainly be able to create the index and when k is greater than 1 or 2, we should return all vectors in the index. I would test some of these edge cases and put them into the tests.

2025-01-12 04:54 UTC, semihsalihoglu-uw commented on src/storage/index/hnsw_index.cpp
> +    if (entryPoint == common::INVALID_OFFSET) {
Interesting. Why would this happen?

2025-01-12 04:54 UTC, semihsalihoglu-uw commented on src/storage/index/hnsw_index.cpp
> +        entryPoint = lowerEntryPoint;
Now that I understand why you have a lowerEntryPoint, maybe rename it to defaultLowerEntryPoint because under normal conditions this just should not happen.

2025-01-12 04:54 UTC, semihsalihoglu-uw commented on src/function/table/call/hnsw/query_hnsw_index.cpp
> +    if (!localState->result.has_value()) {
I finally understand the code. You are implementing the scan logic of chunking some results into Vector_size chunks here. I would write some comments clarifying this because I was not expecting this logic to be in a table function.

2025-01-12 04:54 UTC, semihsalihoglu-uw commented on src/function/table/call/hnsw/query_hnsw_index.cpp
> +    if (!localState->result.has_value()) {
Maybe comment that you have the assumption that the localState->result cannot exist if we have not yet searched. You could also be more explicit and add a boolean variable, e.g., localState->searchPerformed.

2025-01-13 03:43 UTC, ray6080 commented on src/include/storage/index/hnsw_index.h
> +    static std::vector<NodeWithDistance> gatherTopK(max_node_priority_queue_t& result,
Good idea. Renamed to `popTopK`.

2025-01-13 03:45 UTC, ray6080 commented on src/main/client_context.cpp
> +        if (statement->isRewritten) {
Done.

2025-01-13 03:55 UTC, ray6080 commented on src/storage/index/hnsw_index.cpp
> +    if (currentLen >= info.maxDegree) {
Yep.

2025-01-13 03:59 UTC, ray6080 commented on src/include/storage/index/hnsw_index.h
> +    int64_t maxDegree;
Renamed to `degreeThresholdToShrink`.

2025-01-13 04:04 UTC, ray6080 commented on src/include/storage/index/hnsw_config.h
> +// Max connectivity of the upper graph.
Changed to `Mu` and `Ml`.

2025-01-13 04:14 UTC, ray6080 commented on src/storage/index/hnsw_index.cpp
> +        entryPoint = lowerEntryPoint;
Done.

2025-01-13 04:18 UTC, ray6080 commented on src/function/table/call/hnsw/query_hnsw_index.cpp
> +    if (!localState->result.has_value()) {
Done.

2025-01-14 05:17 UTC, ray6080 commented on src/function/table/call/hnsw/query_hnsw_index.cpp
> +    if (localState->numRowsOutput >= localState->result->size()) {
Good point. Added tests for empty and few tuples.

2025-01-14 07:08 UTC, merged